### ISSUE TITLE
The plugin is not supported in Firefox Mobile

### ISSUE THREAD

**Issue by Axiks** [rosset-nocpes/hikka-features#67]
I wanted to install a plugin on the mobile version of Firefox for Android, but it is not supported.

![Screenshot_20241125-031914](https://github.com/user-attachments/assets/d7557b7e-e550-4437-aeca-e304be8b180f)

**Comment by rosset-nocpes** [comment]
Sorry about that, fixed it

**Comment by Axiks** [comment]
Thanks!

Thank you for developing this great plugin. I use it regularly ;)
